### PR TITLE
Resolve #1, add main website files and deploy

### LINKED ISSUE #1: Create AIAA DEIC "Master" Webpage
@jdhaines - 

If it doesn't already exist, can you please create a new repo that establishes an overall AIAA Digital Engineering Integration Committee (DEIC) landing page and add @opinonfischer and I as owners? 

Would like to have this page built so we can have an overall landing page to send folks to for broader communication & coordination. 

Aim is to include on that page:
* Brief description of AIAA DEIC
* Include links to our published Position Papers
* Include a form that allows folks to confirm their interest in joining as a member
* Include calendar of events so folks know when DEIC "all hands" and subgroup meetings are coming up
* Would also like to include a link to each Subcommittee webpage - may be opportunity for each of subcommittee chairs to get an early start / familiarity to coding ... ultimately to prepare us for the coming DEIC Book ...

### PR DESCRIPTION
**Pull request by jdhaines**
See title.  At the requst of @jfmatlik

### CODE REVIEW

**Comment by jdhaines** [comment]
@jfmatlik Just pinging you again on this... ready for merging it in to create the central website?

**Comment by jfmatlik** [comment]
@jdhaines - Yes, want to get the AIAA DEIC central website up, operational and looking good! Just need to get the time to get this over the line on my side! :)

**Review by jfmatlik — APPROVED** [review]

**Comment by jfmatlik** [comment]
Just reviewed and looked good as first pass! Let me know when it is live.

**Review by jfmatlik — APPROVED** [review]
Looks good as first pass. Let me know once the webpage is up and running.

**Comment by jfmatlik** [comment]
@jdhaines - just a quick follow-up on this ... have you built &  published a base AIAA DEIC website for review based on above? If so, please let me know how I can review and update with additional features. A website for a landing page will be very useful for the many folks interested in the DEIC. Would like to have a good, professional site up by/before our next major event (the Dayton Digital Transformation Summit 8-10 May 2024). Thanks!

**Pull request merged**
